#!/usr/bin/env tclsh

# generate_manifest.tcl -- Generate tcl_installer_files.txt from a source directory.
#
# Usage: tclsh generate_manifest.tcl <source_dir> [output_file]
#
# Produces a manifest of all files, relative to <source_dir>, grouped by
# subdirectory with a comment header for each group, suitable for use with
# the Tcl/Tk installer test script.

proc usage {} {
    puts stderr "Usage: tclsh generate_manifest.tcl <source_dir> \[output_file\]"
    exit 1
}

# Recursively collect all files under a directory.
# Returns a list of absolute paths, sorted.
proc collect_files {dir} {
    set results {}
    foreach entry [lsort [glob -nocomplain -directory $dir * .*]] {
        set tail [file tail $entry]
        if {$tail eq "." || $tail eq ".."} continue
        if {[file isdirectory $entry]} {
            lappend results {*}[collect_files $entry]
        } else {
            lappend results $entry
        }
    }
    return $results
}

# Convert a path to use backslashes
proc to_win_path {path} {
    return [string map {/ \\} $path]
}

# ---- Argument handling ----
if {$argc < 1} usage

set source_dir [file normalize [lindex $argv 0]]
set output_file [expr {$argc >= 2 ? [lindex $argv 1] : "tcl_installer_files.txt"}]

if {![file isdirectory $source_dir]} {
    puts stderr "Error: '$source_dir' is not a directory."
    exit 1
}

# ---- Collect and compute relative paths ----
set all_files [collect_files $source_dir]

# Build a dict mapping directory -> list of relative file paths (backslash)
set dir_files [dict create]

foreach abs $all_files {
    set rel [string range $abs [string length $source_dir] end]
    set rel [string trimleft $rel "/\\"]
    set rel [to_win_path $rel]

    set dir [to_win_path [file dirname $rel]]
    # Normalise top-level: file dirname of a bare filename returns "."
    if {$dir eq "."} { set dir "" }

    dict lappend dir_files $dir $rel
}

# ---- Write the manifest ----
set fh [open $output_file w]

puts $fh "# tcl_installer_files.txt -- manifest of files expected after installation."
puts $fh "#"
puts $fh "# Paths are relative to the versioned install root, e.g.:"
puts $fh "#   %LOCALAPPDATA%\\Tcl-Tk\\<major.minor>   (per-user install)"
puts $fh "#   %ProgramFiles%\\Tcl-Tk\\<major.minor>   (all-users install)"
puts $fh "#"
puts $fh "# Lines beginning with # and blank lines are ignored."
puts $fh "# Generated by generate_manifest.tcl from: $source_dir"
puts $fh "# [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S}]"
puts $fh ""

set total 0

foreach dir [lsort [dict keys $dir_files]] {
    # Section comment header
    set label [expr {$dir eq "" ? "(root)" : $dir}]
    puts $fh "# [string repeat - 75]"
    puts $fh "# $label"
    puts $fh "# [string repeat - 75]"

    foreach rel [lsort [dict get $dir_files $dir]] {
        puts $fh $rel
        incr total
    }
    puts $fh ""
}

close $fh

puts "Generated : $output_file"
puts "Source dir: $source_dir"
puts "Files     : $total"
